apiVersion: v1
kind: Pod
metadata:
  name: k8s-pod
  labels:
    app: spring-boot-k8s
spec:
  containers:
    - name: spring-boot-k8s
      image: fincaplus-image:v6
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 8082
